# Generated by Django 4.2.5 on 2023-10-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_subcategory_remove_goods_tra_delete_tra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
