# Generated by Django 4.2.5 on 2023-10-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_subcategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='characteristics',
            field=models.TextField(default=1, verbose_name='Characteristics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
