# Generated by Django 4.2.5 on 2023-10-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_goods_characteristics_goods_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('goods_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.goods')),
                ('processor_type', models.CharField(max_length=50, verbose_name='Processor Type')),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Screen Size')),
            ],
            bases=('categories.goods',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('goods_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.goods')),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Screen Size')),
                ('refresh_rate', models.IntegerField(verbose_name='Refresh Rate')),
            ],
            bases=('categories.goods',),
        ),
        migrations.CreateModel(
            name='PetFood',
            fields=[
                ('goods_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.goods')),
                ('pet_type', models.CharField(max_length=50, verbose_name='Pet Type')),
            ],
            bases=('categories.goods',),
        ),
        migrations.RemoveField(
            model_name='goods',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='text',
        ),
    ]
