# Generated by Django 4.2.5 on 2023-10-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_laptop_monitor_petfood_remove_goods_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='characteristics',
        ),
    ]
