# Generated by Django 4.2.5 on 2023-10-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_laptop_brand_laptop_num_proc_cores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='screen_size',
            field=models.DecimalField(decimal_places=2, default=13, max_digits=4, verbose_name='Screen Size (″)'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ssd',
            field=models.IntegerField(default=200, verbose_name='SSD (GB)'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='video_card_memory_capacity',
            field=models.IntegerField(default=1, verbose_name='Video card memory capacity (GB)'),
        ),
    ]
