# Generated by Django 4.2.5 on 2023-10-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_laptop_screen_size_alter_laptop_ssd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='ssd',
            field=models.IntegerField(default=5, verbose_name='SSD (GB)'),
        ),
    ]
