# Generated by Django 4.2.5 on 2023-10-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_alter_laptop_ssd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='ssd',
        ),
    ]
