# Generated by Django 4.2.5 on 2023-10-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_remove_laptop_ssd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='num_proc_cores',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='operating_memory',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='screen_size',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='video_card',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='video_card_memory_capacity',
        ),
    ]
