# Generated by Django 4.2.5 on 2023-10-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_laptop_num_proc_cores_laptop_operating_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='ssd',
            field=models.IntegerField(default=200, max_length=50, verbose_name='Operating System'),
        ),
    ]
