# Generated by Django 4.2.5 on 2023-10-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0018_remove_laptop_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monitor',
            new_name='PC',
        ),
    ]
